--- !DirTarget
pathToTemplateModelsDirectory:  /Users/elf/mestrado/sourcesMestrado/architecture-representation/filesTemplates/
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/elf/Desktop/output/
pathToProfile: /Users/elf/mestrado/sourcesMestrado/architecture-representation/perfis/smarty.profile.uml
pathToProfileConcern: /Users/elf/mestrado/sourcesMestrado/architecture-representation/perfis/concerns.profile.uml
pathToProfileRelationships: /Users/elf/mestrado/sourcesMestrado/architecture-representation/perfis/relationships.profile.uml
pathToProfilePatterns:  /Users/elf/mestrado/sourcesMestrado/architecture-representation/perfis/patterns.profile.uml

