--- !DirTarget
pathToTemplateModelsDirectory: /Users/elf/Desktop/templates/
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/elf/Desktop/output_testes_2/
pathToProfile:/Users/elf/Desktop/serverUFPR/experiments/PLAS/agm/perfils/smarty.profile.uml
pathToProfileConcern:/Users/elf/Desktop/serverUFPR/experiments/PLAS/agm/perfils/concerns.profile.uml
pathToProfileRelationships:""
pathToProfilePatterns:""
