--- !DirTarget
pathToTemplateModelsDirectory: /Users/elf/Desktop/templates/
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/elf/mestrado/sourcesMestrado/architecture-representation/output/
pathToProfile:/Users/elf/Documents/workspaceModeling/exportacao/output/9316217788/resources/smarty.profile.uml
pathToProfileConcern:/Users/elf/Documents/workspaceModeling/exportacao/output/9316217788/resources/concerns.profile.uml
pathToProfileRelationships:/Users/elf/Documents/workspaceModeling/exportacao/output/9316217788/resources/relationships.profile.uml
pathToProfilePatterns: /Users/elf/Documents/workspaceModeling/exportacao/output/9316217788/resources/patterns.profile.uml