--- !DirTarget
pathToTemplateModelsDirectory: /Users/elf/Desktop/templates/
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/elf/Desktop/output/
pathToProfile: /Users/elf/Documents/workspace/PLAS/mm/smarty.profile.uml
pathToProfileConcern: /Users/elf/Documents/workspace/PLAS/mm/concerns.profile.uml
pathToProfileRelationships: /Users/elf/Documents/workspace/PLAS/mm/relationships.profile.uml
pathToProfilePatterns:  /Users/elf/Documents/workspace/PLAS/mm/patterns.profile.uml
