--- !DirTarget
pathToTemplateModelsDirectory: /Users/elf/Desktop/templates/
directoryToSaveModels: /Users/elf/Desktop/temp/
directoryToExportModels: /Users/elf/Documents/workspaceModeling/testeFinal/
pathToProfile:  /Users/elf/Documents/workspaceModeling/profiles/smarty.profile.uml
pathToProfileConcern:  /Users/elf/mestrado/sourcesMestrado/arquitetura/perfis/concerns.profile.uml
pathToProfileRelationships:  /Users/elf/Documents/workspaceModeling/profiles/relationships.profile.uml
pathToProfilePatterns:  /Users/elf/Documents/workspaceModeling/profiles/patterns.profile.uml

